#!/usr/bin/env bash

# Check the current Bluetooth power state
state=$(bluetoothctl show | grep "Powered:" | awk '{print $2}')

# Toggle Bluetooth power state
if [ "$state" == "yes" ]; then
    bluetoothctl power off
else
    bluetoothctl power on
fi
